### ISSUE TITLE
VampSlmEst file missing

### ISSUE THREAD

**Issue by osmanmusa** [ricedsp/D-AMP_Toolbox#1]
It seems to me that VampSlmEst file required for the VAMP algorithm is missing. If I am wrong, could you please write where to find it.

**Comment by liuyang12** [comment]
Maybe you could have the [GAMPmatlab](http://gampmatlab.wikia.com "GAMPmatlab") package downloaded via the SVN interface, for it is the dependence of the VAMP demos. @osmanmusa 
https://github.com/ricedsp/D-AMP_Toolbox/blob/26957f1514c15191635b212f8b332f2fde76f8c6/ReadMe#L66-L69
