### ISSUE TITLE
DnCNN missing as a denoiser

### ISSUE THREAD

**Issue by liuyang12** [ricedsp/D-AMP_Toolbox#2]
When I was trying to use the [D-AMP_Toolbox](https://github.com/ricedsp/D-AMP_Toolbox "risedep/D_AMP_Toolbox"), I followed the instruction and had [GAMPmatlab](http://gampmatlab.wikia.com "GAMPmatlab") installed and the [NLM](http://www.mathworks.com/matlabcentral/fileexchange/27395-fast-non-local-means-1d--2d-color-and-3d "Non-local Means") and [RWT](https://github.com/ricedsp/rwt "Rice Wavelet Toolbox") compiled.

The issue is that when I was trying to run `Demos/CS_Imaging_Demo_LDAMP.m`, I found that the DnCNN denoiser was missing in `Algorithms/denoise`, as shown in the following code snippets.
https://github.com/ricedsp/D-AMP_Toolbox/blob/26957f1514c15191635b212f8b332f2fde76f8c6/Algorithms/denoise.m#L21-L129

Can the contributor(s) of the [D-AMP_Toolbox](https://github.com/ricedsp/D-AMP_Toolbox "risedep/D_AMP_Toolbox") help with the completion of the DnCNN denoiser? Certainly, I can make my own one. But if the issue is not solved, how could the wonderful D-AMP_Toolbox preserve its integrity? @strikemetz

**Comment by strikemetz** [comment]
Forgot to push. Should be there now.

**Comment by strikemetz** [comment]
Thanks for pointing out! @liuyang12
