### ISSUE TITLE
A question about calculating DIV

### ISSUE THREAD

**Issue by yuhongkang** [ricedsp/D-AMP_Toolbox#4]
Dear author,

I want to ask a question about calculation of DIV.
In your code, you set a Gaussian vector $eta$ 
```
x_tplus1=denoi(pseudo_data,sigma_hat);
eta=randn(1,n); 
epsilon=max(pseudo_data)/1000+eps;  
div=eta*((denoi(pseudo_data+epsilon*eta',sigma_hat)-x_tplus1)/epsilon);
```
and I want to know why it works

**Comment by strikemetz** [comment]
See "Monte-Carlo SURE: A black-box optimization of regularization parameters for general denoising algorithms"
